site_name: Dr Crow Info
theme:
  name: material 
  features:
    - toc.integrate
    - search
    - search.suggest
    - search.highlight
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: blue
      accent: purple 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: darkblue
      accent: lime

nav:
   - Home:'index.md'
   - 'Paediatrics': 
     - 'Cystic Fibrosis': 'cystic_fibrosis.md'
     - 'Precocious Puberty': 'paed_endo_precociousPuberty.md'
     - 'Abdomen': 'paediatrics/paed_abdomen.md'
   - 'Another': 'anotherpage.md'

plugins:
  - social

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/TheDrCrow

